//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.SongTags = new HashSet<SongTag>();
        }
    
        public int SongId { get; set; }
        public string SongTitle { get; set; }
        public string PrimaryArtist { get; set; }
        public int Seconds { get; set; }
        public string Location { get; set; }
        public int BPM { get; set; }
        public bool BPMGuess { get; set; }
    
        public virtual ICollection<SongTag> SongTags { get; set; }
    }
}
